### ISSUE TITLE
树莓派4b中使用Adafruit_Python_DHT读取DHT22一直显示read failed

### ISSUE THREAD

**Issue by gog520** [Wshangji/Govern#6]
- 树莓派4b
- Adafruit_Python_DHT
- python 3.7

**Comment by yanlin-li-java** [comment]
Adafruit_Python_DHT这个库已经停止更新维护了，目前最高支持到树莓派3b

一种方法是更改这个库的中` /Adafruit_Python_DHT/Adafruit_DHT/platform_detect.py `文件，添加对4B的支持

或者是更换*Adafruit_CircuitPython_DHT *库：https://github.com/adafruit/Adafruit_CircuitPython_DHT

` pip3 install adafruit-circuitpython-dht ` 
安装使用

目前发现这个库尽在python3.x中使用，在python2.x中无法安装这个库
